### ISSUE TITLE
events.js:141 Error: read ECONNRESET

### ISSUE THREAD

**Issue by kingmo888** [hexojs/hexo-deployer-ftpsync#12]
`Setup complete.

Collecting
-------------------------------------------------------------
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:544:26)
`
我看到有同学遇到相同的问题，
但在这里我不得不单开一帖了，情况很奇怪。

我两台机器（公司A、家里B）都装有hexo生成器。文章同步用的自己的nas。
最初认识hexo的时候是在公司，因此初代环境在A电脑上，后来将A的hexo文件夹打包到B
以上为前述。

系统环境：WIN7 x64
hexo：A、B都是一致的。
FTP：万网虚拟主机

之前使用'hexo d'一切ok，后来因为转到万网域名要备案，暂停写博就没再更新，后来呢备案下来了，博客重开，在A机器使用hexo d的时候就出现了上述错误。我不知道是公司A的无关hexo的环境变化导致的上述问题还是FTPSYNC本身。
而机器B则依然正常使用。

我试图reinstall hexo，除了deploy配置外其他都有原始安装状态去使用hexo d命令，依旧提示上述错误。

**Comment by leesei** [comment]
Frankly speaking this is just a wrapper around https://github.com/evanplaice/node-ftpsync
Issues should be reported upstream.

**Comment by leesei** [comment]
Track in #11
