### ISSUE TITLE
Can I ignore files by pattern ?

### ISSUE THREAD

**Issue by LTaoist** [hexojs/hexo-deployer-ftpsync#14]
Hey guys !

I use a complex FTP server as my blog server, so I really this great job! However, my server will automatically generate some log files such wwwlog-XXXX , and while I deploy a new version , such files will be removed also.

I notice that it seems that the field 'ignore' can be use to avoid this happen ? but I can not know more details for it. Can anybody help me ? Thanks

**Comment by leesei** [comment]
Please send core feature request to https://github.com/evanplaice/node-ftpsync.
This is just a wrapper plugin.

You are welcome to report updates here.

**Comment by LTaoist** [comment]
@leesei thanks... I just solve it by deploy to a sub-directory , and rewrite url for keep them looks in the same. I thinks this is enough and more clean, so I think I can just close this issuse :-) .
