### ISSUE TITLE
SFTP?

### ISSUE THREAD

**Issue by bxkx** [hexojs/hexo-deployer-ftpsync#15]
Does the plugin support sftp? If not, can I enable it or is it a planned feature?

**Comment by PavelVanecek** [comment]
I guess not. There is some activity in the jsftp library, see: https://github.com/sergi/jsftp/issues/157

**Comment by stevenjoezhang** [comment]
You can try this plugin: https://www.npmjs.com/package/hexo-deployer-sftp
