### ISSUE TITLE
Notice belongs in README

### ISSUE THREAD

**Issue by emazurek** [hexojs/hexo-deployer-ftpsync#17]
The following notice certainly belongs in the README.md. 

Notice: This application will delete files and directories on the remote server to match the local machine. Use this application in production at your own risk.

**Comment by bastimori** [comment]
https://www.npmjs.com/package/ftpsync
Notice: The core functionality to push files to a remote server is now fully implemented. Until the timestamp comparison logic is worked out, updates (ie overwriting files) are determined solely by comparing file sizes. This is not ftp-deploy. This application will delete files and directories on the remote server to match the local machine. Use this application in production at your own risk.

**Comment by emazurek** [comment]
Thanks @bastimori, updated PR

**Comment by NoahDragon** [comment]
Merged. Thanks.
