### ISSUE TITLE
Ignoring remote folders ?

### ISSUE THREAD

**Issue by Bridouz** [hexojs/hexo-deployer-ftpsync#19]
Hi,

I really enjoy the _deploy_ function for Hexo but I was wondering if it's possible to exclude a remote folder during the sync process. I have a folder on my server that is independant from Hexo and I don't want him to be remove during the process.

I know there is an _ignore_ setting for FTPSync in `_config.yml` but I don't understand how to ignore a folder.

Is it possible ?

Thanks

**Comment by NoahDragon** [comment]
Yes, it is possible. Just list ignored folder in that setting.

Ref: https://www.npmjs.com/package/ftpsync#ftpsyncsettings

**Comment by Bridouz** [comment]
Hi,

thanks for the answer but I don't understand how to ignore one whole folder.
I tried : 
```
ignore: /hashover/
ignore: ./hashover/
ignore: /hashover/*
ignore: ./hashover/*
```
But none of these work and my directory called hashover (with subdirectories and files inside) is deleted no matter what I try.

**Comment by NoahDragon** [comment]
Could you please try the following?

```
ignore: "/hashover/"
```

**Comment by Bridouz** [comment]
Not working either.

I may not understand the purpose of FTPSync. The directory *Hashover* is only present on my remote webserver not in the public folder when I generate Hexo.

**Comment by NoahDragon** [comment]
If it is on remote, then you may need to remove it manually, the FTPSync will upload the files and folders under the public or .deploy folder (which one I'm not clear). For those files/folders existing on remote, it won't delete them.

**Comment by Bridouz** [comment]
Mmh ok. Thanks

I still don't understand how to ignore the deletion of my *hashover* remote folder when launching the command `hexo deploy`. Seems that I will not use that command and deploy by hand over an ftp software :)

**Comment by NoahDragon** [comment]
It only ignores the folder/file on local machine, not the remote. 

You can also put the hashover folder under the source folder, and then hexo generate will copy it to public/deploy folder.
