### ISSUE TITLE
ftpsync seems to never finish !

### ISSUE THREAD

**Issue by ghost** [hexojs/hexo-deployer-ftpsync#21]
the command hexo deploy ends with the message:
INFO Deploy done:ftpsync
BUT never exit and returns to the terminal !

**Comment by NoahDragon** [comment]
Could you please paste you _config.yml?

**Comment by phicarre** [comment]
My machine is debian/jessie. I am root
here is the end of the hexo deploy command:
```
Consolidation complete.

Committing
-------------------------------------------------------------
Commit complete.
INFO  Deploy done: ftpsync
```

I am obliged to type <ctrl>Z to end the command

**Comment by benoitg** [comment]
I have this very same issue

**Comment by NoahDragon** [comment]
Could you please check if this issue resolved in #28 ?

**Comment by phicarre** [comment]
no resolved
I live with !

**Comment by stevenjoezhang** [comment]
Sorry for the late reply. I have already refactored this plugin. If the issue persists, please feel free to report it again. The installation method for the new version is: `npm i hexo-deployer-ftpsync@0.2.0`
