### ISSUE TITLE
Got Exception on "TypeError: Cannot read property 'on' of undefined"

### ISSUE THREAD

**Issue by NoahDragon** [hexojs/hexo-deployer-ftpsync#24]
![image](https://cloud.githubusercontent.com/assets/5704064/21280661/4ef7e3d8-c3b5-11e6-93f8-4a6fe5ec3512.png)

Is this some bug?

hexojs/hexo-deployer-ftpsync#16

**Comment by zzming** [comment]
I also met for this problem

**Comment by Zohar727** [comment]
have the same problem

**Comment by ic6** [comment]
I also met for this problem

**Comment by stevenjoezhang** [comment]
Sorry for the late reply. I have already refactored this plugin. If the issue persists, please feel free to report it again. The installation method for the new version is: `npm i hexo-deployer-ftpsync@0.2.0`
