### ISSUE TITLE
upload issues

### ISSUE THREAD

**Issue by JWHK852** [hexojs/hexo-deployer-ftpsync#44]
```java
Consolidation complete.

Committing
-------------------------------------------------------------
- /wwwroot/2020/05/10/Hello World created successfuly
MKDIRs complete.
```

Everythings seem ok but it will stop at here forever.
And I cheak my server , I see Hexo create a file call 'index.html' in 'Hello World' folder. But it is empty inside the index.html .

**Comment by m8** [comment]
also, if you can add timeout for deploy it would be a good enhancement

**Comment by punksinatra** [comment]
@JWHK852 did they ever get resolved? I am experiencing the same issue, it gets stucked all the time

**Comment by stevenjoezhang** [comment]
I have also noticed that there are usability issues with this plugin, please join the discussion here: https://github.com/hexojs/hexo-deployer-ftpsync/issues/51
