### ISSUE TITLE
This plugin does not work on hexo: 4.2.1.

### ISSUE THREAD

**Issue by csmov** [hexojs/hexo-deployer-ftpsync#51]
This plugin does not work on hexo: 4.2.1. Windows 10 2004
Tested on different ftp servers. Including tested locally on FileZilla Server.
Connected creates folders and that's it. no mistakes. Files does not transfer.

you can check it yourself

**Comment by m8** [comment]
yep, i have been troubling with same issue on 4.2.1. is this repo still maintained?

**Comment by m8** [comment]
are there any results?

**Comment by HelloLudger** [comment]
I have the same problem.
It stops after `MKDIRs complete`.

No error thrown.

I am on Windows 10.

**Comment by aussiealf** [comment]
Same was hoping this would highlight what is going on, there isn't anything logged to screen, I do find that if I leave it it does eventually transfer a file but it takes about 10-15mins per basic html file.

**Comment by stevenjoezhang** [comment]
"Thank you for the feedback. I have also noticed that there are usability issues with this plugin (it depends on a library that hasn't been updated for many years). I am currently working on a refactor: https://github.com/hexojs/hexo-deployer-ftpsync/pull/148
