### ISSUE TITLE
Deployment use hexo-ployer-ftpsync error

### ISSUE THREAD

**Issue by otherfish** [hexojs/hexo-deployer-ftpsync#7]
INFO  60 files generated in 2.33 s
INFO  Deploying: ftpsync
Setup
Setup complete.

Collecting
Collection complete.

Consolidating
Consolidation complete.

Committing
MKDIRs complete.
ftp.put failed.
Additions failed.
Commit failed.
Commit complete.
E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\asy
nc\lib\async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                                   ^
Error: Callback was already called.
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:43:36
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:694:17
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:173:37
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\lib\ftpsy
nc.js:277:7
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:697:13
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:52:16
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:267:21
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:44:16
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:694:17
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:173:37
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\lib\ftpsy
nc.js:228:13
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:52:16
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:363:13
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:52:16
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:325:29
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:44:16
    at E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modu
les\async\lib\async.js:360:17
    at Socket.<anonymous> (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modul
es\ftpsync\lib\ftpsync.js:475:13)
    at Socket.f (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync
\node_modules\jsftp\node_modules\once\once.js:16:25)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

**Comment by ellioseven** [comment]
I get the same issue

**Comment by ellioseven** [comment]
I managed to fix my issue by specifying the `remote` property:

```
deploy:
- type: ftpsync
  host: ftp.example.com
  user: 
  pass: 
  verbose: true
  remote: '/public_html'
```

**Comment by otherfish** [comment]
oh,thank you reply,this is my solution:

>http://huabuyu.net/2015/08/30/%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2hexo%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E5%88%B0%E8%99%9A%E6%8B%9F%E4%BA%91%E4%B8%BB%E6%9C%BA/
